### ISSUE TITLE
请问migrate中查询索引存在时所用的名称和实际添加的索引名称不一致是为什么

### ISSUE THREAD

**Issue by ximenhaoziye** [nfjBill/gorm-driver-dm#1]
比如：SELECT COUNT(*) FROM USER_INDEXES WHERE TABLE_NAME = 'USERS_DEPARTMENTS' AND INDEX_NAME = 'IDX_USERS_DEPARTMENTS_IDX_USERS_DEPARTMENTS_DEPARTMENT_ID'
实际添加进数据库中是IDX_USERS_DEPARTMENTS_DEPARTMENT_ID，这样子会导致下一次migrate时报错索引已存在，而且在第一次使用migrte时并不能创建索引

**Comment by nfjBill** [comment]
达梦每张表只允许有一个聚集索引

**Comment by ximenhaoziye** [comment]
您说的聚集索引是指联合索引么，我例举的是单个索引字段，只是代码会自动拼接这么长，而且我并没有做更改删除操作，只是多次执行migrate时期望他会自动判断该索引是否存在是否需要创建，但是实际上它查询时自动拼接上表名，并且拼接两遍，这是我不能理解的

**Comment by nfjBill** [comment]
回头我看下达梦文档吧，它支持就能弄。

**Comment by nfjBill** [comment]
抱歉，昨天太忙了没有看清你的问题，已修复
